### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by frostbane** [shazow/sqlalchemygrate#8]
I'm getting the same error as with
[https://stackoverflow.com/questions/32422819/kallithea-sqlite-database-to-mysql-database](https://stackoverflow.com/questions/32422819/kallithea-sqlite-database-to-mysql-database)

**Comment by shazow** [comment]
I posted an answer in the stackoverflow question.

I don't actively use sqlalchemygrate right now, but I have no reason to believe that it's broken?

If it is, fixes are welcome.

**Comment by frostbane** [comment]
![OK](http://st.depositphotos.com/2926881/3775/v/110/depositphotos_37758305-stock-illustration-like-thumbs-up-symbol-icon.jpg)

@shazow Thanks
